
#pragma once
#define NO_ACTION_FUNCTION
#define NO_ACTION_MACRO
#define NO_ACTION_ONESHOT

#define EXTRA_SHORT_COMBOS
#define TAPPING_TERM_PER_KEY

#define TAP_HOLD_CAPS_DELAY 0
#define TAP_CODE_DELAY 0 
#define MK_KINETIC_SPEED
