
AUDIO_ENABLE = no
AUTO_SHIFT_ENABLE = no
BACKLIGHT_ENABLE = no
BOOTMAGIC_ENABLE = no
COMMAND_ENABLE = no
CONSOLE_ENABLE = no
DEFERRED_EXEC_ENABLE = no
DYNAMIC_TAPPING_TERM_ENABLE = no
ENCODER_ENABLE = no
EXTRAFLAGS += -flto
EXTRAKEY_ENABLE = no
LTO_ENABLE = yes
KEY_LOCK_ENABLE = no
LEADER_ENABLE = no
MAGIC_ENABLE = no
MIDI_ENABLE = no
NKRO_ENABLE = no
POINTING_DEVICE_ENABLE = no
SLEEP_LED_ENABLE = no
SPACE_CADET_ENABLE = no
STENO_ENABLE = no
SWAP_HANDS_ENABLE = no
TERMINAL_ENABLE = no
TRI_LAYER_ENABLE = no
VARIABLE_TRACE = no

## UNICODEMAP_ENABLE = yes
## UNICODE_ENABLE = yes

CAPS_WORD_ENABLE = yes
COMBO_ENABLE = yes
KEY_OVERRIDE_ENABLE = yes
MOUSEKEY_ENABLE = yes
TAP_DANCE_ENABLE = yes
